name: lemp

recipe: lemp

config:
  webroot: www
  php: '8.3'
  xdebug: true
  config:
    vhosts: config/default.conf
    php:    config/php.ini

proxy:
  web:
    - www.lemp.lndo.site
  mailhog:
    - mail.lemp.lndo.site
  pma:
    - pma.lemp.lndo.site

services:
  appserver:
    build_as_root:
      - apt-get update -y
      - apt-get install -y wget curl
    overrides:
      environment:
        PHP_MEMORY_LIMIT: 1G
  cache:
    type: redis
    persist: true
    node:
      type: node:20
      build:
      - npm install
      scanner: false
      ssl: false
      sslExpose: false
  database:
    type: mariadb:11.3
    portforward: true
  pma:
    type: phpmyadmin
    hosts: database
  mailhog:
    type: mailhog:v1.0.1
    portforward: false
    hogfrom:
      - appserver

tooling:
  redis-cli:
    service: cache
  node:
    service: node
  npm:
    service: node
